function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Breakpoint", file = "media/maps/Breakpoint/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "Cruise Ship in KY", file = "media/maps/Cruise Ship in KY/spawnpoints.lua" },
		{ name = "Eerie A", file = "media/maps/Eerie A/spawnpoints.lua" },
		{ name = "Eerie B", file = "media/maps/Eerie B/spawnpoints.lua" },
		{ name = "Eerie C", file = "media/maps/Eerie C/spawnpoints.lua" },
		{ name = "Eerie Country", file = "media/maps/Eerie Country/spawnpoints.lua" },
		{ name = "Eerie D", file = "media/maps/Eerie D/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "Fort Knox linked to Eerie Country", file = "media/maps/Fort Knox linked to Eerie Country/spawnpoints.lua" },
		{ name = "Near Fort Knox", file = "media/maps/Near Fort Knox/spawnpoints.lua" },
		{ name = "To Bedford Falls", file = "media/maps/To Bedford Falls/spawnpoints.lua" },
		{ name = "To Eerie Country", file = "media/maps/To Eerie Country/spawnpoints.lua" },
		{ name = "Fort Rock Ridge", file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "InGameMaps_Main", file = "media/maps/InGameMaps_Main/spawnpoints.lua" },
		{ name = "Eerie Country_map", file = "media/maps/Eerie Country_map/spawnpoints.lua" },
		{ name = "From Bedford Falls to Fort Knox_map", file = "media/maps/From Bedford Falls to Fort Knox_map/spawnpoints.lua" },
		{ name = "Fort Knox linked to Eerie Country_map", file = "media/maps/Fort Knox linked to Eerie Country_map/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Lincoln Regional Airport", file = "media/maps/Lincoln Regional Airport/spawnpoints.lua" },
		{ name = "Muldraugh Fire Department", file = "media/maps/Muldraugh Fire Department/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua" },
		{ name = "PapaVilleModMap", file = "media/maps/PapaVilleModMap/spawnpoints.lua" },
		{ name = "RabbitHashKY", file = "media/maps/RabbitHashKY/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua" },
		{ name = "Riverwood", file = "media/maps/Riverwood/spawnpoints.lua" },
		{ name = "From Bedford Falls to Fort Knox", file = "media/maps/From Bedford Falls to Fort Knox/spawnpoints.lua" },
		{ name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua" },
		{ name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua" },
		{ name = "NewDenver", file = "media/maps/NewDenver/spawnpoints.lua" },
		{ name = "Rosebery", file = "media/maps/Rosebery/spawnpoints.lua" },
		{ name = "Silverton", file = "media/maps/Silverton/spawnpoints.lua" },
		{ name = "NewDenver_Connection_map", file = "media/maps/NewDenver_Connection_map/spawnpoints.lua" },
		{ name = "TrimbleCountyPowerStation", file = "media/maps/TrimbleCountyPowerStation/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
		{ name = "VardellRaceway", file = "media/maps/VardellRaceway/spawnpoints.lua" },
		{ name = "MotoriousExpandedSpawnZones", file = "media/maps/MotoriousExpandedSpawnZones/spawnpoints.lua" },
		{ name = "West Point Fire Department", file = "media/maps/West Point Fire Department/spawnpoints.lua" },
		{ name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua" },
		{ name = "Wilbore", file = "media/maps/Wilbore/spawnpoints.lua" },
		{ name = "Wildberries", file = "media/maps/Wildberries/spawnpoints.lua" },
		{ name = "Winchester, KY", file = "media/maps/Winchester, KY/spawnpoints.lua" },
	}
end
