function SpawnRegions()
    return {
        {name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua"},
        {name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua"},
        {name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua"},
        {name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua"},
        {name = "Eerie B", file = "media/maps/Eerie B/spawnpoints.lua"},
        {name = "Eerie C", file = "media/maps/Eerie C/spawnpoints.lua"},
        {name = "Eerie Country", file = "media/maps/Eerie Country/spawnpoints.lua"},
        {name = "Eerie D", file = "media/maps/Eerie D/spawnpoints.lua"},
        {name = "Farm house", file = "media/maps/Farm house/spawnpoints.lua"},
        {name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua"},
        {name = "li_township", file = "media/maps/li_township/spawnpoints.lua"},
        {name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua"},
        {name = "Kingsmouth", file = "media/maps/Kingsmouth/spawnpoints.lua"},
        {name = "NewDenver", file = "media/maps/NewDenver/spawnpoints.lua"},
        {name = "Rosebery", file = "media/maps/Rosebery/spawnpoints.lua"},
        {name = "Silverton", file = "media/maps/Silverton/spawnpoints.lua"},
        {name = "EdsAutoSalvage", file = "media/maps/EdsAutoSalvage/spawnpoints.lua"},
        {name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua"},
        {name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua"},
        {name = "Near Fort Knox", file = "media/maps/Near Fort Knox/spawnpoints.lua"},
        {name = "To Bedford Falls", file = "media/maps/To Bedford Falls/spawnpoints.lua"},
        {name = "To Eerie Country", file = "media/maps/To Eerie Country/spawnpoints.lua"},
        {name = "From Bedford Falls to Fort Knox", file = "media/maps/From Bedford Falls to Fort Knox/spawnpoints.lua"},
        {name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua"},
        {name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua"},
        {name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua"},
        {name = "ParkingLot", file = "media/maps/ParkingLot/spawnpoints.lua"},
        {name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua"},
        {name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua"},
        {name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua"},
        {name = "HouseLuisMatrioshka", file = "media/maps/HouseLuisMatrioshka/spawnpoints.lua"},
        {name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua"},
        {name = "chernaville", file = "media/maps/chernaville/spawnpoints.lua"},
        {name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua"},
        {name = "Wildberries", file = "media/maps/Wildberries/spawnpoints.lua"},
        {name = "MREX", file = "media/maps/MREX/spawnpoints.lua"},
        {name = "Greenleaf", file = "media/maps/Greenleaf/spawnpoints.lua"},
        {name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua"},
        {name = "Lande Desolate Camping", file = "media/maps/Lande Desolate Camping/spawnpoints.lua"},
        {name = "coryerdon", file = "media/maps/coryerdon/spawnpoints.lua"},
        {name = "West Point Fire Department", file = "media/maps/West Point Fire Department/spawnpoints.lua"},
        {name = "Muldraugh Fire Department", file = "media/maps/Muldraugh Fire Department/spawnpoints.lua"},
        {name = "Northwest Blockade", file = "media/maps/Northwest Blockade/spawnpoints.lua"},
        {name = "Northwest Blockade", file = "media/maps/Northwest Blockade/spawnpoints.lua"},
        {name = "Lone", file = "media/maps/Lone/spawnpoints.lua"},
        {name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua"},
        {name = "Bendys Bunker v2", file = "media/maps/Bendys Bunker v2/spawnpoints.lua"},
        {name = "Irvington, KY", file = "media/maps/Irvington, KY/spawnpoints.lua"},
        {name = "Irvington, KY", file = "media/maps/Irvington, KY/spawnpoints.lua"},
        {name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua"},
        {name = "CigaroHouse", file = "media/maps/CigaroHouse/spawnpoints.lua"},
        {name = "Hilltop", file = "media/maps/Hilltop/spawnpoints.lua"},
        {name = "RabbitHashKY", file = "media/maps/RabbitHashKY/spawnpoints.lua"},
        {name = "Hopewell, KY", file = "media/maps/Hopewell, KY/spawnpoints.lua"},
        {name = "Hopewell, KY", file = "media/maps/Hopewell, KY/spawnpoints.lua"},
        {name = "Elysium_Island", file = "media/maps/Elysium_Island/spawnpoints.lua"},
        {name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua"},
        {name = "KS10YL", file = "media/maps/KS10YL/spawnpoints.lua"},
        {name = "RC10YL", file = "media/maps/RC10YL/spawnpoints.lua"},
        {name = "Heavens Hill", file = "media/maps/Heavens Hill/spawnpoints.lua"},
        {name = "Cryo Compound", file = "media/maps/Cryo Compound/spawnpoints.lua"},
        {name = "Chestown", file = "media/maps/Chestown/spawnpoints.lua"},
        {name = "EastTownofRiverside", file = "media/maps/EastTownofRiverside/spawnpoints.lua"},
        {name = "TheEyeLake", file = "media/maps/TheEyeLake/spawnpoints.lua"},
        {name = "Lincoln Regional Airport", file = "media/maps/Lincoln Regional Airport/spawnpoints.lua"},
        {name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua"},
        {name = "Westoutskirts-shippingCo", file = "media/maps/Westoutskirts-shippingCo/spawnpoints.lua"},
        {name = "TeraMart", file = "media/maps/TeraMart/spawnpoints.lua"},
        {name = "PapaVilleModMap", file = "media/maps/PapaVilleModMap/spawnpoints.lua"},
        {name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua"},
        {name = "Petroville", file = "media/maps/Petroville/spawnpoints.lua"},
        {name = "riversidemansion", file = "media/maps/riversidemansion/spawnpoints.lua"},
        {name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua"},
        {name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua"},
        {name = "orchidwood", file = "media/maps/orchidwood/spawnpoints.lua"},
        {name = "LastMinutePrepper", file = "media/maps/LastMinutePrepper/spawnpoints.lua"},
        {name = "LastMinutePrepperReloaded", file = "media/maps/LastMinutePrepperReloaded/spawnpoints.lua"},
        {name = "Winchester, KY", file = "media/maps/Winchester, KY/spawnpoints.lua"},
        {name = "CorOTRroad", file = "media/maps/CorOTRroad/spawnpoints.lua"},
        {name = "VardellRaceway", file = "media/maps/VardellRaceway/spawnpoints.lua"},
        {name = "Chinatown_EX", file = "media/maps/Chinatown_EX/spawnpoints.lua"},
        {name = "Wilbore", file = "media/maps/Wilbore/spawnpoints.lua"},
        {name = "Lalafell's Fortress", file = "media/maps/Lalafell's Fortress/spawnpoints.lua"},
        {name = "UncleRedsBunker", file = "media/maps/UncleRedsBunker/spawnpoints.lua"},
        {name = "UncleRedsBunkerRedux", file = "media/maps/UncleRedsBunkerRedux/spawnpoints.lua"},
        {name = "Homepie", file = "media/maps/Homepie/spawnpoints.lua"},
        {name = "Springwood", file = "media/maps/Springwood/spawnpoints.lua"},
        {name = "Cedar Hill", file = "media/maps/Cedar Hill/spawnpoints.lua"},
        {name = "BBL", file = "media/maps/BBL/spawnpoints.lua"},
        {name = "betsysfarm", file = "media/maps/betsysfarm/spawnpoints.lua"},
        {name = "MuldraughCheckpoint", file = "media/maps/MuldraughCheckpoint/spawnpoints.lua"},
        {name = "MuldraughCheckpoint[H]", file = "media/maps/MuldraughCheckpoint[H]/spawnpoints.lua"},
        {name = "TerminusTWD", file = "media/maps/TerminusTWD/spawnpoints.lua"},
        {name = "spencermansionlootable", file = "media/maps/spencermansionlootable/spawnpoints.lua"},
        {name = "Louisville_Quarantine_Zone", file = "media/maps/Louisville_Quarantine_Zone/spawnpoints.lua"},
        {name = "Speck", file = "media/maps/Speck/spawnpoints.lua"},
        {name = "Shortrest County", file = "media/maps/Shortrest County/spawnpoints.lua"},
        {name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua"},
        {name = "Waterlocked Pharmaceutical Factory", file = "media/maps/Waterlocked Pharmaceutical Factory/spawnpoints.lua"},
        {name = "Louisville_River_Marina", file = "media/maps/Louisville_River_Marina/spawnpoints.lua"},
        {name = "Louisville_Riverboat", file = "media/maps/Louisville_Riverboat/spawnpoints.lua"},
        {name = "Nettle Township", file = "media/maps/Nettle Township/spawnpoints.lua"},
        {name = "Fort_Boonesborough", file = "media/maps/Fort_Boonesborough/spawnpoints.lua"},
        {name = "NSCarWorkshop", file = "media/maps/NSCarWorkshop/spawnpoints.lua"},
        {name = "Louisville Mall Base", file = "media/maps/Louisville Mall Base/spawnpoints.lua"},
        {name = "St Paulo", file = "media/maps/St Paulo/spawnpoints.lua"},
        {name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua"},
        {name = "Portland", file = "media/maps/Portland/spawnpoints.lua"},
        {name = "The Yacht", file = "media/maps/The Yacht/spawnpoints.lua"},
        {name = "LCV2", file = "media/maps/LCV2/spawnpoints.lua"},
        {name = "ranger's_homestead_map", file = "media/maps/ranger's_homestead_map/spawnpoints.lua"},
        {name = "Wellsburg Lake", file = "media/maps/Wellsburg Lake/spawnpoints.lua"},
        {name = "railroadhouse", file = "media/maps/railroadhouse/spawnpoints.lua"},
        {name = "Hunter'sBase_map", file = "media/maps/Hunter'sBase_map/spawnpoints.lua"},
        {name = "elliotpondec", file = "media/maps/elliotpondec/spawnpoints.lua"},
        {name = "WestPointGatedCommunity", file = "media/maps/WestPointGatedCommunity/spawnpoints.lua"},
        {name = "Greenport", file = "media/maps/Greenport/spawnpoints.lua"},
        {name = "rustyrascalsroadkillrestaurant", file = "media/maps/rustyrascalsroadkillrestaurant/spawnpoints.lua"},
        {name = "lvinternationalairport", file = "media/maps/lvinternationalairport/spawnpoints.lua"},
        {name = "Foxwood", file = "media/maps/Foxwood/spawnpoints.lua"},
        {name = "PortCityKY", file = "media/maps/PortCityKY/spawnpoints.lua"},
        {name = "DayOfTheDead", file = "media/maps/DayOfTheDead/spawnpoints.lua"},
        {name = "Leavenburg", file = "media/maps/Leavenburg/spawnpoints.lua"},
        {name = "RiversideMapFix", file = "media/maps/RiversideMapFix/spawnpoints.lua"},
        {name = "The Oasis", file = "media/maps/The Oasis/spawnpoints.lua"},
        {name = "C_Madriguera", file = "media/maps/C_Madriguera/spawnpoints.lua"},
        {name = "leavensburgcoreydonroad", file = "media/maps/leavensburgcoreydonroad/spawnpoints.lua"},
        {name = "Jasperville", file = "media/maps/Jasperville/spawnpoints.lua"},
        {name = "Canvasback", file = "media/maps/Canvasback/spawnpoints.lua"},
        {name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua"},
        {name = "Otr", file = "media/maps/Otr/spawnpoints.lua"}
    }
end
